// Generated by CoffeeScript 1.7.1
(function() {
  var Control, Display, Example, React;

  React = require("react");

  Display = require("./Display");

  Control = require("./Control");

  Example = React.createClass({
    render: function() {
      require("./style.less");
      return <div className="module-example">
			<Display />
			<div>
				<Control action="increment" label="+1" />
				<Control action="decrement" label="-1" />
				<Control action="reset" label="Reset" />
			</div>
		</div>;
    }
  });

  module.exports = Example;

}).call(this);
